click_cosmetics/urls.py
from django.contrib import admin
from django.urls import path, include

# from core.views import signup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('', include("core.urls")),
]

core/urls.py
from django.urls import path
from . import views

from .views import BusinessList, BusinessDetail, SignUpClientView, SignUpBusinessView, AppointmentView, DiaryView

app_name = "core"

urlpatterns = [
    path('', views.search, name="search"),
    path('business-list/', BusinessList.as_view(), name="business_list"),
    path('<int:pk>/', BusinessDetail.as_view(), name="business_detail"),
    path('business-signup/', SignUpBusinessView.as_view(), name="business_form"),
    path('client-signup/', SignUpClientView.as_view(), name="client_create"),
    path('<int:business_id>/appointment/', AppointmentView.as_view(), name="appointment_form"),
    path('diary/', DiaryView.as_view(), name="diary_form")

    # path('treatments/<int:pk>/', views.treatments_page, name="treatments_page"),
]

core/models.py
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class TreatmentType(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class WorkDay(models.Model):
    daychoices = (
        (7, 'Sunday'),
        (1, 'Monday'),
        (2, 'Tuesday'),
        (3, 'Wednesday'),
        (4, 'Thursday'),
        (5, 'Friday'),
        (6, 'Saturday'),
    )
    day = models.CharField(default="" ,max_length=15)
    # day_int = models.IntegerField(blank=True, null=True, choices=daychoices)

    def __str__(self):
        return self.day
        # return self.get_day_int_display()


class Business(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='business',default=None )
    phone = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField()
    treatments = models.ManyToManyField(TreatmentType, blank=True)
    days = models.ManyToManyField(WorkDay, blank=True)
    location = models.CharField(max_length=20)
    start_hour = models.TimeField(default="08:00")
    end_hour = models.TimeField(default="16:00")

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('core:business_detail',kwargs={'pk':self.pk})


class Client(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='client')
    location = models.CharField(max_length=200)
    phone = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.user.username

class Appointment(models.Model):
    business = models.ForeignKey(Business,on_delete=models.CASCADE,related_name='appointments')
    client = models.ForeignKey(Client,on_delete=models.CASCADE,related_name='appointments')
    treatment = models.ForeignKey(TreatmentType,on_delete=models.CASCADE)
    day = models.DateField()
    time = models.TimeField(default="08:00")

    def get_absolute_url(self):
        return reverse('core:appointment_form',kwargs={'business_id':self.business_id})

core/forms.py
import datetime
from django import forms
from core.models import  Business

class AForm(forms.Form):
    # experienceYears = Field(max_length=2, choices=expChoices, default=0, blank=True)
    treatments = forms.ChoiceField(label='treatments', widget=forms.RadioSelect)
    dates = forms.ChoiceField(label='choose date')
    hours = forms.ChoiceField(label='choose hour')

    def __init__(self, treatments_obj, expChoices, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['treatments'].choices = ((t.id, t.name) for t in treatments_obj)
        self.fields['dates'].choices = expChoices
        self.fields['hours'].choices = expChoices


class SignUpBusinessForm(forms.ModelForm):
    username = forms.CharField(
        label='Business name',
        max_length=200, widget=forms.TextInput(attrs={'class': 'from-control'}))
    first_name = forms.CharField(label='Full name',max_length=100)
    email = forms.EmailField(label='Email', max_length=200)
    password = forms.CharField(label='Password', max_length=200, widget=forms.PasswordInput)

    class Meta:
        model= Business
        fields = ['username','first_name','email','password','phone','location','description','treatments','days','start_hour','end_hour']
        widgets = {
            'start_hour' : forms.Select(
                attrs={'class': 'from-control'},
                choices=((f'{x}:00', f'{x}:00') for x in range(6, 24))),
            'end_hour': forms.Select(choices=((f'{x}:00', f'{x}:00') for x in range(6, 24)))
        }

class SignUpClientForm(forms.Form):
    username = forms.CharField(
        label='User name',
        max_length=200, widget=forms.TextInput(attrs={'class': 'from-control'}))
    first_name = forms.CharField(max_length=100)
    email = forms.EmailField(label='Email', max_length=200)
    password = forms.CharField(label='Password', max_length=200, widget=forms.PasswordInput)
    location = forms.CharField(label='Location', max_length=200)
    phone = forms.CharField(label='Phone', max_length=200)


class AppointmentForm(forms.Form):
    treatments = forms.ChoiceField(label='treatments', widget=forms.RadioSelect)
    dates = forms.ChoiceField(label='choose date')
    hours = forms.ChoiceField(label='choose hour')

    def __init__(self, *args, **kwargs):
        self.treatments_obj = kwargs.pop('treatments_obj', None)
        self.expChoices = kwargs.pop('expChoices', None)
        self.hours = kwargs.pop('hours',None)
        super().__init__(*args, **kwargs)
        self.fields['treatments'].choices = ((t.id, t.name) for t in self.treatments_obj)
        self.fields['dates'].choices = self.expChoices
        self.fields['hours'].choices = self.hours

core/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import AccessMixin, LoginRequiredMixin
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.views.generic import ListView, DetailView, FormView, TemplateView
from .forms import AForm, SignUpBusinessForm, SignUpClientForm, AppointmentForm
from .models import Business, TreatmentType, User, Client, Appointment
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
import datetime


class BusinessList(ListView):
    template_name = 'core/business.html'
    model = Business
    def get_queryset(self):
        qs = super().get_queryset()
        treatment = self.request.GET.get('treatment')
        fname = self.request.GET.get('fname')
        bname = self.request.GET.get('bname')
        location = self.request.GET.get('location')
        if treatment:
            qs = qs.filter(treatments__name__icontains=treatment)
        if fname:
            qs = qs.filter(user__first_name__icontains=fname)
        if bname:
            qs = qs.filter(user__name__icontains=bname)
        if location:
            qs = qs.filter(location__icontains=location)

        return qs


class BusinessDetail(DetailView):
    template_name = 'core/busines_detail.html'
    model = Business
    # queryset = Business.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['apo_list'] = self.get_object().appointments.all()
        return context



def search(request):
    return render(request, 'core/search.html')


class NoneLoginPermitted(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            raise Http404
        return super().dispatch(request, *args, **kwargs)


class SignUpBusinessView(NoneLoginPermitted, FormView):
    template_name = 'registration/signup_business.html'
    form_class = SignUpBusinessForm
    success_url = reverse_lazy('core:search')

    def form_valid(self, form):
        data = form.cleaned_data
        user = User.objects.create(
            username=data['username'],
            first_name=data['first_name'],
            email=data['email'],
        )

        user.set_password(data['password'])
        user.save()
        # treatments_qs = TreatmentType.objects.filter(name__contains=data['treatments'])
        print(data['treatments'])
        business = Business.objects.create(
            user=user,
            phone=data['phone'],
            location=data['location'],
            description=data['description'],
            start_hour=data['start_hour'],
            end_hour=data['end_hour']
        )
        business.treatments.set(data['treatments']),
        business.days.set(data['days']),

        business.save()
        login(self.request, user)
        return super(SignUpBusinessView, self).form_valid(form)


class SignUpClientView(NoneLoginPermitted, FormView):
    template_name = 'registration/signup_client.html'
    form_class = SignUpClientForm
    success_url = reverse_lazy('core:search')

    def form_valid(self, form):
        data = form.cleaned_data
        user = User.objects.create(
            username=data['username'],
            first_name=data['first_name'],
            email=data['email'],
        )
        user.set_password(data['password'])
        user.save()
        Client.objects.create(
            user=user,
            phone=data['phone'],
            location=data['location']
        )
        login(self.request, user)
        return super(SignUpClientView, self).form_valid(form)


class AppointmentView(FormView):
    template_name = 'core/appointment.html'
    form_class = AppointmentForm
    success_url = reverse_lazy('core:search')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            if Client.objects.filter(user=self.request.user):
                return super().dispatch(request, *args, **kwargs)
            raise Http404
        return HttpResponseRedirect(reverse_lazy('login'))

    def hours(self):
        bid = self.kwargs['business_id']
        b = get_object_or_404(Business, pk=bid)
        appointments_for_business = b.appointments.all()
        return [(
            a.day,
            a.time.strftime("%H:%M"),
        ) for a in appointments_for_business]


    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        dt = timezone.now()
        dates = []
        bid = self.kwargs['business_id']
        b = get_object_or_404(Business, pk=bid)

        daysWork_obj = Business.objects.get(id=bid).days.all()
        day_list = [x.day for x in daysWork_obj]
        for x in range(30):
            a = dt + datetime.timedelta(days=x)
            if a.date().strftime('%A') in day_list:
                dates.append(a)
        l = [x.date() for x in dates ]
        expChoices = [(x, x.strftime('%d/%m/%Y %A')) for x in l]
        treatments_obj = Business.objects.get(id=bid).treatments.all()

        kwargs['treatments_obj'] = treatments_obj
        kwargs['expChoices'] = expChoices

        start_hour = Business.objects.get(id=bid).start_hour.hour
        end_hour = Business.objects.get(id=bid).end_hour.hour
        hours = []
        for hour in range(start_hour , end_hour+1):
            hours.append((hour,datetime.time(hour,00).strftime("%H:%M")))
        kwargs['hours'] =hours
        return kwargs
    # def dispatch(self, request, *args, **kwargs):
    #     if request.user.is_authenticated and Client.objects.filter(user=self.request.user).exists():
    #         return super().dispatch(request, *args, **kwargs)
    #     return redirect(reverse('core:search'))

    def form_valid(self, form):
        data = form.cleaned_data
        business_id = self.kwargs['business_id']
        # treat_id = self.kwargs['treatments']
        treatment_id = data['treatments']
        user = self.request.user
        date_input =  data['dates']
        day = datetime.datetime.strptime(date_input, '%Y-%m-%d').date()
        time =  data['hours']
        a = Appointment.objects.create(
            business_id=business_id,
            client=user.client,
            treatment_id=treatment_id,
            day=day,
            time=datetime.time(int(time),00).strftime("%H:%M")

        )
        return super(AppointmentView, self).form_valid(form)

class DiaryView(LoginRequiredMixin, TemplateView):
    template_name = 'core/diary.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['appointments'] = Appointment.objects.filter(
            Q(business__user=self.request.user) |
            Q(client__user=self.request.user)
        )
        return context

core/templates/core/appointment.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="jumbotron text-center" style="position: fixed">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">
            SAVE
        </button>

    </form>
    {{ view.hours|json_script:"hoursUsed" }}
    </div>
{% endblock %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Click Cosmetic</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Merienda+One|Oleo+Script&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extracss %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'core:search' %}">Click Cosmetic</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">About Us</a>
            </li>

            {% if user.is_authenticated %}
                <li class="nav-item logout">
                    <a class="nav-link" href="{% url 'logout' %}">logout</a>
                </li>
                <li class="nav-item diary" aria-labelledby="navbarDropdownMenuLink">
                    <a class="nav-link" href="{% url 'core:diary_form' %}">Your Diary</a>
                </li>
            {% endif %}
            {% if not user.is_authenticated %}
                <li class="nav-item login">
                    <a class="nav-link" href="{% url 'login' %}">login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block business%}{% endblock %}
{% block search %}{% endblock %}
<div class="content">{% block content %}{% endblock %}</div>

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="{% static 'script.js' %}"></script>
{% endblock %}


</body>
</html>

core/templates/core/busines_detail.html
{% extends 'core/base.html' %}
{% block business %}
    <title>Treatments</title>

    <div class="jumbotron text-center">
    <div class = "head">
        <p>{{ object.description }}</p>
        <p>By {{ object.user.first_name }}</p>
    </div>
    <div style="font-size: 2.5vh">
        <p><u>You can find here:</u></p>
        {% for treat in object.treatments.all %}
            <p>{{ treat.name }}</p>
        {% endfor %}
        <a class="btn" href="{% url 'core:appointment_form' object.id %}">Make an appointment</a>
    </div>
    </div>
{% endblock business %}
{% block scripts %}

{% endblock %}

core/templates/core/business.html
{% extends 'core/base.html' %}
{% block content %}
<title>business</title>

        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Business</th>
                <th scope="col">Treatments</th>
                <th scope="col">Work Days</th>
                <th scope="col">Work Hours</th>
                <th scope="col">Location</th>
            </tr>
            </thead>
            <tbody>
            {% for business in object_list %}
                <tr>
                <td><a href="{{ business.get_absolute_url }}">{{ business.user.username }}</a>
                </td>
                <td>{% for treat in business.treatments.all %}
                    <p>{{ treat.name }}</p>
                {% endfor %}
                </td>
                <td>{% for day in business.days.all %}
                    <p>{{ day.day }}</p>
                {% endfor %}
                </td>
                <td>
                    <p>{{ business.start_hour }}-{{ business.end_hour }}</p>
                </td>
                                <td>
                    <p>{{ business.location }}</p>
                </td>
            {% endfor %}
            </tr>

            </tbody>
        </table>
{% endblock content %}

core/templates/core/diary.html
{% extends 'core/base.html' %}
{% block content %}
    <title>Diary</title>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col"> Business/Client</th>
            <th scope="col"> Treatments</th>
            <th scope="col"> Day</th>
            <th scope="col"> Hour</th>
        </tr>
        </thead>
        <tbody>
        {% for a in appointments %}
            {% if a.client %}
            <tr>
                <td><p>{{ a.client.user.username }}</p>
                </td>
                <td><p>{{ a.treatment }}</p>
                </td>
                <td><p>{{ a.day }}</p>
                </td>
                <td>
                    <p>{{ a.time }}</p>
                </td>

            </tr>
            {% else %}
            <tr>
                <td><a href="{{ a.get_absolute_url }}"> {{ a.business.username }}</a>
                </td>
                <td><p>{{ a.treatment }}</p>
                </td>
                <td><p>{{ a.day }}</p>
                </td>
                <td>
                    <p>{{ a.time }}</p>
                </td>

            </tr>
            {% endif %}
        {% endfor %}

        </tbody>
    </table>
{% endblock content %}

core/templates/core/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

core/templates/core/search.html
{% extends 'core/base.html' %}
{% block search %}
    <title>Search</title>
    <div style="position: fixed">
        <form class="search" action="{% url 'core:business_list' %}">

            <label for="treatment"><div>Treatment</div>
                <input type="text" id="treatment" name="treatment" value=""></label>
            <label for="fname"><div>Business owner name</div>
                <input type="text" id="fname" name="fname" value=""></label>
            <label for="bname"><div>Business name</div>
                <input type="text" id="bname" name="bname" value=""></label>
            <label for="location"><div>Location</div>
                <input type="text" id="location" name="location" value=""></label>
            <button class="btn" type="submit">Search</button>
        </form>
    </div>
{% endblock search %}

core/templates/core/treatments.html
{% extends 'core/base.html' %}
{% block content %}
    <title>Treatments</title>

    <div>
        <form>
            {{ form.as_p }}
        </form>
    </div>
{% endblock content %}